services:
  rasa:
    image: rasa/rasa:3.6.17-full
    command: ["run", "--enable-api", "--cors", "*", "--debug"]
    ports:
      - "5005:5005"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./domain.yml:/app/domain.yml
      - ./config:/app/config
      - ./endpoints.yml:/app/endpoints.yml
      - ./credentials.yml:/app/credentials.yml
    depends_on:
      - actions

  actions:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    command: [ "start" ]
    volumes:
      - ./actions:/app/actions