[project]
name = "rasa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rasa-pro[channels,nlu,standard]>=3.15.2",
    "rasa-sdk>=3.15.0",
]
